version: "3.3"

services:
  qix-engine:
    image: qlikcore/engine:12.657.0
    restart: always
    command: |
      -S AcceptEULA=${ACCEPT_EULA}
      -S StandardReload=0
      -S DocumentDirectory=/data
    ports:
      - 9076:9076
    volumes:
      - ./data:/data

  chrome:
    image: browserless/chrome:1.33-puppeteer-2.0.0
    ports:
      - 3000:3000
